package pl.accepted.challenge.exceptions;

/**
 * Created by Marcin on 2016-03-25.
 */
public class UserNotFoundException extends Exception {
}
